export { HomePage } from './HomePage'
export { GamePage } from './GamePage'
export { GameDetailPage } from './GameDetailPage'
export { MyBetsPage } from './MyBetsPage'
export { AccountPage } from './AccountPage'
export { OtherPage } from './OtherPage'